# Disable redundant logs 
hydra:  
  output_subdir: null  
  run:  
    dir: .

experiment:
  log_dir: outputs/
  save_dir: weights/
  seed: 420
  verbose: True
  use_gpu: True

model: 
  type: models.FullyConnected

datasets:
  root: data/
  type: torchvision.datasets.MNIST
  validation_split: 0.2

dataloaders: 
  shuffle: True
  n_batches: 32

transforms:
  # applied to training and validation dataset
  default:
    - type: torchvision.transforms.ToTensor
    - type: torchvision.transforms.Normalize
      args:
        mean: [0.5]
        std: [0.5]

  # applied to training set in addition to default
  augment:
    - type: torchvision.transforms.RandomHorizontalFlip
      args:
        p: 0.5

optimizer: 
  type: torch.optim.Adam
  args: 
    lr: 0.001

criterion:
  type: torch.nn.CrossEntropyLoss 

metrics: [accuracy, f1_score]

training: 
  n_epochs: 20
  # number of epochs otherwise
  early_stopping: 2